### PR TITLE
fix(ui): Enable clipboard copying in insecure browser contexts

### LINKED ISSUE #5541: bug: copy to clipboard not working on self-hosted langfuse without https cert setup
### Describe the bug

Copy to clipboard buttons in langfuse web do not work on a self-hosted langfuse instance.

The cause seems to be that most browsers, including Chrome and Firefox, disable the clipboard functionality without https, but self hosted instances often are for personal/internal use and do not have https certs set up.

Other projects like Open-WebUI have implemented an workaround that [makes use of textArea](https://github.com/open-webui/open-webui/blob/e4d7d41df6d913d33910561090fd5d1afcd997f3/src/lib/utils/index.ts#L305-L345). Could similar workarounds be implemented for langfuse? At least the check button after pressing the copy button should not show when copy didn't work.

### To reproduce

* Load a self-hosted langfuse web without https cert setup.
* Use any copy to clipboard button.

### SDK and container versions

_No response_

### Additional information

_No response_

### Are you interested to contribute a fix for this bug?

No

### PR DESCRIPTION
**Pull request by akshitvijay**
## What does this PR do?

Implements a fallback method for scenarios lacking Clipboard API support in insecure contexts (e.g., HTTP resources not delivered locally).

### Fixes

Fixes [#5541](https://github.com/langfuse/langfuse/issues/5541)

### Summary of Changes

- Added an `execCommand`-based fallback for clipboard copy.
- Resolves clipboard copy failures when a self-hosted Langfuse instance doesn't have HTTPS certificates.
- The issue arises because the document is served in a non-secure context, where the Clipboard API is unavailable.
- Introduced a common workaround using `document.execCommand`.
- **Important Caveat:** `execCommand` is deprecated and may lose support in browsers in the future.

### Related Reading

- [Original Issue](https://github.com/langfuse/langfuse/issues/5541)
- [Clipboard API's need for secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure)
- [Secure Contexts Explained](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure)
- [execCommand Deprecation](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#:~:text=Document%3A%20execCommand()%20method-,Deprecated,-%3A%20This%20feature)

### Loom Recordings

- [Before Fix](https://www.loom.com/share/032041fced9042da8d02e2287c38e958?sid=ab229c5d-1f13-4083-9dab-7e0b919fe033)
- [After Fix](https://www.loom.com/share/d0ee45842f664aee8e6f160553ba660b?sid=97f434cb-3e5e-4b1a-b0f8-39d6d204bd22)

## Type of change

* [X] Bug fix (non-breaking change which fixes an issue)
* [ ] Chore (refactoring code, technical debt, workflow improvements)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Refactor (does not change functionality, e.g. code style improvements, linting)
* [ ] This change requires a documentation update

## Mandatory Tasks

* [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

* I haven't added tests that prove my fix is effective or that my feature works
* I haven't checked if new and existing unit tests pass locally with my changes

----

> [!IMPORTANT]
> Adds `execCommand` fallback for clipboard copying in insecure contexts across multiple components.
> 
>   - **Behavior**:
>     - Implements `copyTextToClipboard` in `clipboard.ts` to use `execCommand` as a fallback for insecure contexts.
>     - Replaces `navigator.clipboard.writeText` with `copyTextToClipboard` in `publish-object-switch.tsx`, `CodeJsonViewer.tsx`, `Codeblock.tsx`, `MarkdownViewer.tsx`, `GenerationOutput.tsx`, and `PromptSelectionDialog.tsx`.
>   - **Caveats**:
>     - `execCommand` is deprecated and may not be supported in future browser versions.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=langfuse%2Flangfuse&utm_source=github&utm_medium=referral)<sup> for 2c6b4b2574839bb876eb9c7f040869962d5ee120. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: web/src/utils/clipboard.ts [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+ * Note:
+ * - Local resources like http://localhost, http://127.0.0.1, and http://*.localhost are NOT affected.
+ *
+ * Important:
+ * - This fallback method uses `execCommand`, which is deprecated.
+ * - It will stop working once browsers fully remove support for `execCommand`.
+ */
+const _unsafeNonSecureCopyToClipboard = (text: string) => {
+  try {
+    const textArea = document.createElement("textarea");
```
[the remark this answers is not in the document]
Comment (akshitvijay) [reply web/src/utils/clipboard.ts:20]: Added this

**Comment by akshitvijay** [comment]
My first PR here, have tried following the contribution guide and some closed PRs I could reference.  Highly appreciate any constructive feedback.

**Comment by marcklingen** [comment]
thanks for the contributions, @marliessophie can you have a look into this?

File: web/src/utils/clipboard.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+};
+
+/**
+ * Copy text to clipboard using clipboard api or fallback to _unsafeNonSecureCopyToClipboardfor non secure contexts
+ *
+ * @param text - Text to copy to clipboard
+ * @returns Promise<void>
+ */
+export const copyTextToClipboard = async (text: string) => {
+  if (navigator.clipboard) {
```
Comment (marliessophie) [inline web/src/utils/clipboard.ts:41]: _Suggestion:_ You might want to check for both existence and permission to use the Clipboard API by verifying that `navigator.clipboard.writeText` is of type function.

File: web/src/utils/clipboard.ts [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+  try {
+    const textArea = document.createElement("textarea");
+    textArea.value = text;
+    textArea.style.position = 'fixed'; 
+    textArea.style.left = '-9999px';
+    document.body.appendChild(textArea);
+    textArea.focus();
+    textArea.select();
+    document.execCommand("copy");
+    document.body.removeChild(textArea);
```
Comment (marliessophie) [inline web/src/utils/clipboard.ts:28]: Nice, this uses proper DOM cleanup.

**Review by marliessophie — APPROVED** [review]
Hey, thanks so much @akshitvijay for posting this code. Your code looks secure for its intended purpose and falls back to what is still a standard method in all common browsers. The documentation is also clear. Happy to merge this! Just left a single suggestion you can consider, otherwise I would merge this and close the loop here.   

So sorry again for being slow here, I dropped the ball here.

File: web/src/components/publish-object-switch.tsx [hunk 4]
```diff
@@ -96,7 +97,7 @@ const Base = (props: {
 
   const copyUrl = () => {
     setIsCopied(true);
-    void navigator.clipboard.writeText(window.location.href);
+    void copyTextToClipboard(window.location.href);
```
[the remark this answers is not in the document]
Comment (akshitvijay) [reply web/src/components/publish-object-switch.tsx:100]: Not modifying the existing behaviour to avoid unintended effects

File: web/src/utils/clipboard.ts (hunk 2 above)
Comment (akshitvijay) [reply web/src/utils/clipboard.ts]: Thank you for the suggestion. I have updated the check to 
`typeof navigator.clipboard?.writeText === "function"`

**Comment by akshitvijay** [comment]
@marliessophie I have included the suggestion you made. I have resolved a conflict that came due to the latest release and rebased with main. This should work now. Also I totally understand the delay in the review. No bother.

**Comment by marliessophie** [comment]
> @marliessophie I have included the suggestion you made. I have resolved a conflict that came due to the latest release and rebased with main. This should work now. Also I totally understand the delay in the review. No bother.

Great, thanks so much! I will merge this to main :)
